name: PHP Composer / PHPUnit tests

on:
  push:
    branches: [ main ]
    paths:
      - 'php/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'php/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      working-directory: ./php

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: ./php

    - name: Run tests
      run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests
      working-directory: ./php